export default {
  code: 0,
  message: 'SUCCESS',
  requestId: null,
  data: {
    benefitListAble: [
      {
        benefitNo: '1010002',
        benefitName: '一起喝免配送费',
        useDesc: '外卖订单可用',
        bannerDesc: '今日邀好友「一起喝」可享免配送费',
        balance: '1',
        canUseToday: true,
        subscribedIs: null,
        isWeeklyBenefit: false,
        dayOfWeek: null,
        privilegeType: 1,
        bcardExperienceType: null,
        weight: 4,
      },
    ],
    benefitListDisable: [
      {
        benefitNo: '1010006',
        benefitName: '生日饮茶有礼',
        useDesc: '生日饮茶特权',
        bannerDesc: '生日有喜！今日下单享单杯5折',
        balance: '0',
        canUseToday: null,
        subscribedIs: null,
        isWeeklyBenefit: false,
        dayOfWeek: null,
        privilegeType: null,
        bcardExperienceType: null,
        weight: 2,
      },
    ],
    benefitListWeekly: [
      {
        benefitNo: '1010008',
        benefitName: '周二免费加料',
        useDesc: '点茶可免费加1份小料',
        bannerDesc: '今日下单可享免费加料',
        balance: '1',
        canUseToday: false,
        subscribedIs: null,
        isWeeklyBenefit: true,
        dayOfWeek: 2,
        privilegeType: 0,
        bcardExperienceType: null,
        weight: 0,
      },
      {
        benefitNo: '1010003',
        benefitName: '周四一起喝随机立减',
        useDesc: '至少3人参与，随机减免',
        bannerDesc: '今日邀好友「一起喝」可享随机立减',
        balance: '1',
        canUseToday: false,
        subscribedIs: null,
        isWeeklyBenefit: true,
        dayOfWeek: 4,
        privilegeType: 1,
        bcardExperienceType: null,
        weight: 0,
      },
    ],
    newProductInfo: null,
    haveFillBirthday: false,
  },
};
