export default {
  data: [
    {
      id: 5237,
      image_id: 1111810,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/11/17/7e88859a3738488da69f760c6bd01260.gif-app',
      image_width: '300',
      image_height: '300',
      title: '取茶页面loading ',
      description: null,
      type: null,
      content: '',
      value: null,
      position: 'take_tea',
      policy_type: 0,
      ad_position_index: null,
      ad_direction_type: null,
      sort: 0,
      category_id: null,
      product_id: null,
      general_product_id: null,
      activity_id: null,
      os: null,
      app_id: null,
      self_app: false,
      show_channel: null,
      show_total_times: null,
      show_ceiling: true,
      show_effect_type: null,
      show_effect_time: null,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: null,
    },
    {
      id: 5234,
      image_id: 1111741,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/11/16/e58f6c2f32e94b6385ab5eba5461ad9d.jpg-app',
      image_width: '750',
      image_height: '600',
      title: '大陆',
      description: null,
      type: '1',
      content: '下单免排队，外卖送上门',
      value: null,
      position: 'share',
      policy_type: 0,
      ad_position_index: 0,
      ad_direction_type: 0,
      sort: 5,
      category_id: null,
      product_id: null,
      general_product_id: null,
      activity_id: null,
      os: null,
      app_id: null,
      self_app: true,
      show_channel: 15,
      show_total_times: null,
      show_ceiling: true,
      show_effect_type: 1,
      show_effect_time: 1,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: null,
    },
    {
      id: 5865,
      image_id: 1111016,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/11/16/46befac08d1e4832bca9c4c63363deed.jpg-app',
      image_width: '510',
      image_height: '690',
      title: '水牛乳焙茶',
      description: null,
      type: '4',
      content: '',
      value: null,
      position: 'product',
      policy_type: 0,
      ad_position_index: 0,
      ad_direction_type: 1,
      sort: 29,
      category_id: null,
      product_id: 5433,
      general_product_id: null,
      activity_id: null,
      os: null,
      app_id: null,
      self_app: true,
      show_channel: 15,
      show_total_times: null,
      show_ceiling: false,
      show_effect_type: 1,
      show_effect_time: 1,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: null,
    },
    {
      id: 5843,
      image_id: 1107749,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/11/12/a6375ba6dbf842169bae07455ce2b10a.jpg-app',
      image_width: '1062',
      image_height: '1437',
      title: '酷黑莓桑2023',
      description: null,
      type: '4',
      content: '',
      value: null,
      position: 'product',
      policy_type: 0,
      ad_position_index: 0,
      ad_direction_type: 1,
      sort: 30,
      category_id: null,
      product_id: 5412,
      general_product_id: null,
      activity_id: null,
      os: null,
      app_id: null,
      self_app: true,
      show_channel: 15,
      show_total_times: null,
      show_ceiling: false,
      show_effect_type: 1,
      show_effect_time: 1,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: null,
    },
    {
      id: 5740,
      image_id: 1093037,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/10/30/b23f7d3541ea4e7fbd1f3b279fbe6cab.jpg-app',
      image_width: '510',
      image_height: '690',
      title: '芭比',
      description: null,
      type: '4',
      content: '',
      value: null,
      position: 'product',
      policy_type: 0,
      ad_position_index: 0,
      ad_direction_type: 1,
      sort: 33,
      category_id: null,
      product_id: 5272,
      general_product_id: null,
      activity_id: null,
      os: null,
      app_id: null,
      self_app: true,
      show_channel: 15,
      show_total_times: -1,
      show_ceiling: true,
      show_effect_type: 1,
      show_effect_time: 1,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: 1087,
    },
    {
      id: 5719,
      image_id: 1087149,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/10/26/f1c57dd8c7b24f109c6517b19cc9acc2.jpg-app',
      image_width: '1063',
      image_height: '1438',
      title: '配方揭秘',
      description: null,
      type: '6',
      content: '',
      value: null,
      position: 'product',
      policy_type: 0,
      ad_position_index: 0,
      ad_direction_type: 1,
      sort: 34,
      category_id: null,
      product_id: null,
      general_product_id: null,
      activity_id: 695,
      os: null,
      app_id: null,
      self_app: true,
      show_channel: 5,
      show_total_times: null,
      show_ceiling: true,
      show_effect_type: 1,
      show_effect_time: 1,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: null,
    },
    {
      id: 5394,
      image_id: 1042780,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/09/11/156435fb823b415c81d2bea5fa15f377.jpg-app',
      image_width: '480',
      image_height: '651',
      title: '周一领券',
      description: null,
      type: '3',
      content: '',
      value: '/pages/activity/monday_deliver_free/index',
      position: 'product',
      policy_type: 0,
      ad_position_index: 0,
      ad_direction_type: 1,
      sort: 35,
      category_id: null,
      product_id: null,
      general_product_id: null,
      activity_id: null,
      os: null,
      app_id: null,
      self_app: true,
      show_channel: 5,
      show_total_times: null,
      show_ceiling: true,
      show_effect_type: 1,
      show_effect_time: 1,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: null,
    },
    {
      id: 2426,
      image_id: 1098638,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/11/03/9560adaca48e47b6b8f989f17fa74f1b.jpg-app',
      image_width: '510',
      image_height: '690',
      title: '要真果+要真奶-强制展示在最后-新版',
      description: '',
      type: '1',
      content: '',
      value: null,
      position: 'product',
      policy_type: 0,
      ad_position_index: 0,
      ad_direction_type: 1,
      sort: 36,
      category_id: null,
      product_id: null,
      general_product_id: null,
      activity_id: null,
      os: null,
      app_id: null,
      self_app: true,
      show_channel: 15,
      show_total_times: null,
      show_ceiling: false,
      show_effect_type: 1,
      show_effect_time: 1,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: null,
    },
    {
      id: 5347,
      image_id: 1098474,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/11/03/cf1f57c4ae8544d297e8151564683ce6.jpg-app',
      image_width: '1064',
      image_height: '1439',
      title: '热饮推荐 常规',
      description: null,
      type: '5',
      content: '',
      value: null,
      position: 'product',
      policy_type: 0,
      ad_position_index: 0,
      ad_direction_type: 1,
      sort: 37,
      category_id: 7,
      product_id: null,
      general_product_id: null,
      activity_id: null,
      os: null,
      app_id: null,
      self_app: true,
      show_channel: 15,
      show_total_times: null,
      show_ceiling: false,
      show_effect_type: 1,
      show_effect_time: 1,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: null,
    },
    {
      id: 2435,
      image_id: 1110174,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/11/14/33e814076d4042248eb257d65912e29b.jpg-app',
      image_width: '510',
      image_height: '690',
      title: '轻负担推荐',
      description: '',
      type: '5',
      content: '',
      value: null,
      position: 'product',
      policy_type: 0,
      ad_position_index: 0,
      ad_direction_type: 1,
      sort: 39,
      category_id: 307,
      product_id: null,
      general_product_id: null,
      activity_id: null,
      os: null,
      app_id: null,
      self_app: true,
      show_channel: 15,
      show_total_times: null,
      show_ceiling: false,
      show_effect_type: 1,
      show_effect_time: 1,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: null,
    },
    {
      id: 5110,
      image_id: 1098489,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/11/03/c09f4ed488084fdd81e514f1a30870e1.jpg-app',
      image_width: '1063',
      image_height: '1438',
      title: '葡萄大单品',
      description: null,
      type: '4',
      content: '',
      value: null,
      position: 'product',
      policy_type: 0,
      ad_position_index: 0,
      ad_direction_type: 1,
      sort: 42,
      category_id: null,
      product_id: 2280,
      general_product_id: null,
      activity_id: null,
      os: null,
      app_id: null,
      self_app: true,
      show_channel: 15,
      show_total_times: null,
      show_ceiling: true,
      show_effect_type: 1,
      show_effect_time: 1,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: null,
    },
    {
      id: 5111,
      image_id: 1098494,
      image_url:
        'https://go.cdn.heytea.com/storage/product/2023/11/03/0c284340b72c447a9f88c4c5bfd0a3bd.jpg-app',
      image_width: '1063',
      image_height: '1439',
      title: '烤黑糖大单品',
      description: null,
      type: '4',
      content: '',
      value: null,
      position: 'product',
      policy_type: 0,
      ad_position_index: 0,
      ad_direction_type: 1,
      sort: 43,
      category_id: null,
      product_id: 1256,
      general_product_id: null,
      activity_id: null,
      os: null,
      app_id: null,
      self_app: true,
      show_channel: 15,
      show_total_times: null,
      show_ceiling: true,
      show_effect_type: 1,
      show_effect_time: 1,
      screen_type: null,
      screen_width: null,
      screen_height: null,
      shop_id: null,
    },
  ],
  hash_code: 933056775,
};
